#워크 플로우 이름
name: Publish Package to GitHub Packages

# 언제 이 workflow를 실행하나?
on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

# 워크 플로우 실행을 위한 작업 정의
jobs:
  # publish-packages JobID 추가
  publish-packages:
    runs-on: ubuntu-latest # 우분투 최신 버전에서 실행

    permissions:
        contents: read # 저장소 코드를 체크아웃하기 위한 읽기 권한
        packages: write # 패키지에 대한 쓰기 권한

    steps:
      # 체크아웃 저장소 코드
      - name: Checkout repository
        uses: actions/checkout@v4

      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle build 및 GitHub Packages에 배포
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          # GITHUB_TOKEN은 GitHub Actions가 자동으로 생성해주는 시크릿 토큰
          # 위 permissions 블록에서 부여한 권한을 갖게 됨
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
